export const FETCH_IDEAS_START = 'FETCH_IDEAS_START';
export const FETCH_IDEAS_SUCCESS = 'FETCH_IDEAS_SUCCESS';
export const FETCH_IDEAS_FAILURE = 'FETCH_IDEAS_FAILURE';
export const CREATE_IDEA = 'CREATE_IDEA';
